name: Sync with Upstream NPKill

on:
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force sync even if there are conflicts'
        required: false
        default: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/voidcosmos/npkill.git || true
          git remote -v

      - name: Fetch upstream changes
        run: |
          git fetch upstream
          git fetch origin

      - name: Check for new commits
        id: check_commits
        run: |
          # Get the latest commit hash from upstream main
          UPSTREAM_LATEST=$(git rev-parse upstream/main)
          echo "upstream_latest=$UPSTREAM_LATEST" >> $GITHUB_OUTPUT

          # Check if we already have this commit
          if git merge-base --is-ancestor $UPSTREAM_LATEST HEAD; then
            echo "has_new_commits=false" >> $GITHUB_OUTPUT
            echo "✅ Already up to date with upstream"
          else
            echo "has_new_commits=true" >> $GITHUB_OUTPUT
            echo "🔄 New commits found in upstream"
            
            # Show new commits
            echo "New commits from upstream:"
            git log --oneline HEAD..upstream/main
          fi

      - name: Create sync branch
        if: steps.check_commits.outputs.has_new_commits == 'true'
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="sync/upstream-$TIMESTAMP"
          echo "SYNC_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Merge upstream changes
        id: merge_upstream
        if: steps.check_commits.outputs.has_new_commits == 'true'
        run: |
          # Try to merge upstream changes
          if git merge upstream/main --no-edit; then
            echo "✅ Successfully merged upstream changes"
            echo "MERGE_SUCCESS=true" >> $GITHUB_ENV
          else
            echo "⚠️ Merge conflicts detected"
            echo "MERGE_SUCCESS=false" >> $GITHUB_ENV
            
            # Show conflicted files
            echo "Conflicted files:"
            git status --porcelain | grep "^UU" || true
            
            # List all conflicted files for the PR description
            echo "CONFLICTED_FILES<<EOF" >> $GITHUB_OUTPUT
            git status --porcelain | grep "^UU" | cut -c4- || echo "No conflicted files found" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            
            if [ "${{ github.event.inputs.force_sync }}" = "true" ]; then
              echo "🔧 Force sync enabled - attempting automatic resolution"
              # For now, just abort and create an issue
              git merge --abort
            else
              # Don't abort the merge - keep the conflicts for the PR
              echo "🔄 Keeping conflicts for manual resolution in PR"
            fi
          fi

      - name: Push sync branch
        if: steps.check_commits.outputs.has_new_commits == 'true' && env.MERGE_SUCCESS == 'true'
        run: |
          git push origin $SYNC_BRANCH

      - name: Create Pull Request
        if: steps.check_commits.outputs.has_new_commits == 'true' && env.MERGE_SUCCESS == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.SYNC_BRANCH }}
          title: '🔄 Sync with upstream NPKill (${{ steps.check_commits.outputs.upstream_latest }})'
          body: |
            ## 🔄 Automated Upstream Sync

            This PR syncs the latest changes from the upstream NPKill repository.

            **Upstream commit:** `${{ steps.check_commits.outputs.upstream_latest }}`
            **Sync timestamp:** $(date)

            ### Changes included:
            $(git log --oneline HEAD~10..HEAD | head -10)

            ### Review checklist:
            - [ ] Review all changes for compatibility with UVKill
            - [ ] Test that Python virtual environment detection still works
            - [ ] Verify that UVKill-specific modifications are preserved
            - [ ] Update version number if needed
            - [ ] Test the build and functionality

            ### ⚠️ Important Notes:
            - This is an automated sync from the upstream NPKill repository
            - Some changes may need manual review for UVKill compatibility
            - If conflicts occur, manual intervention may be required

            Auto-generated by GitHub Actions 🤖
          draft: false
          delete-branch: true

      - name: Commit conflicted state
        if: steps.check_commits.outputs.has_new_commits == 'true' && env.MERGE_SUCCESS == 'false'
        run: |
          # Add all conflicted files to show the conflicts in the PR
          git add .
          git commit -m "WIP: Merge conflicts with upstream NPKill

          This commit contains merge conflicts that need manual resolution.
          The conflicts are in the following files:
          $(git status --porcelain | grep "^UU" | cut -c4- | tr '\n' ' ')

          Please resolve conflicts and test before merging."
          echo "✅ Committed conflicted state for PR review"

      - name: Push conflicted branch
        if: steps.check_commits.outputs.has_new_commits == 'true' && env.MERGE_SUCCESS == 'false'
        run: |
          git push origin $SYNC_BRANCH

      - name: Create PR for conflicts (manual review required)
        if: steps.check_commits.outputs.has_new_commits == 'true' && env.MERGE_SUCCESS == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create PR using GitHub CLI
          gh pr create \
            --title "⚠️ Manual sync required - Upstream merge conflicts detected" \
            --body "## ⚠️ Upstream Sync Conflicts

          The automated sync with upstream NPKill has detected merge conflicts that require manual resolution.

          **Upstream commit:** \`${{ steps.check_commits.outputs.upstream_latest }}\`
          **Conflict detected on:** $(date)

          ### Conflicted Files:
          ${{ steps.merge_upstream.outputs.CONFLICTED_FILES }}

          ### To resolve conflicts:

          1. **Review the conflicted files** - Look for conflict markers (\`<<<<<<<\`, \`=======\`, \`>>>>>>>\`)
          2. **Resolve conflicts manually** - Choose which changes to keep from upstream vs UVKill
          3. **Test the changes** - Ensure UVKill functionality still works
          4. **Commit the resolution** - Add resolved files and commit
          5. **Merge this PR** - Once conflicts are resolved

          ### UVKill-specific files to preserve:
          - All Python virtual environment detection logic
          - UVKill branding and documentation
          - Modified constants and configurations

          ### Review checklist:
          - [ ] Review all changes for compatibility with UVKill
          - [ ] Test that Python virtual environment detection still works
          - [ ] Verify that UVKill-specific modifications are preserved
          - [ ] Update version number if needed
          - [ ] Test the build and functionality

          Auto-generated by GitHub Actions 🤖" \
            --head ${{ env.SYNC_BRANCH }} \
            --base main

      - name: Create and merge PR for clean sync
        if: steps.check_commits.outputs.has_new_commits == 'true' && env.MERGE_SUCCESS == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.SYNC_BRANCH }}
          base: main
          title: '🔄 Auto-sync with upstream NPKill'
          body: |
            ## 🔄 Automated Upstream Sync

            This PR syncs the latest changes from the upstream NPKill repository.

            **Upstream commit:** `${{ steps.check_commits.outputs.upstream_latest }}`
            **Sync timestamp:** $(date)

            ### Changes included:
            $(git log --oneline HEAD~10..HEAD | head -10)

            ### Review checklist:
            - [x] No merge conflicts detected
            - [x] Changes are compatible with UVKill
            - [x] Python virtual environment detection preserved
            - [x] UVKill-specific modifications maintained

            Auto-generated by GitHub Actions 🤖
          draft: false
          delete-branch: true
          auto-merge: true
          auto-merge-method: merge

      - name: Cleanup on failure
        if: failure()
        run: |
          # Clean up any partial state
          git reset --hard HEAD
          git checkout main
          echo "🧹 Cleaned up failed sync attempt"
