name: Sync with Upstream NPKill

on:
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force sync even if there are conflicts'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/voidcosmos/npkill.git || true
          git remote -v

      - name: Fetch upstream changes
        run: |
          git fetch upstream
          git fetch origin

      - name: Check for new commits
        id: check_commits
        run: |
          # Get the latest commit hash from upstream main
          UPSTREAM_LATEST=$(git rev-parse upstream/main)
          echo "upstream_latest=$UPSTREAM_LATEST" >> $GITHUB_OUTPUT

          # Check if we already have this commit
          if git merge-base --is-ancestor $UPSTREAM_LATEST HEAD; then
            echo "has_new_commits=false" >> $GITHUB_OUTPUT
            echo "✅ Already up to date with upstream"
          else
            echo "has_new_commits=true" >> $GITHUB_OUTPUT
            echo "🔄 New commits found in upstream"
            
            # Show new commits
            echo "New commits from upstream:"
            git log --oneline HEAD..upstream/main
          fi

      - name: Create sync branch
        if: steps.check_commits.outputs.has_new_commits == 'true'
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="sync/upstream-$TIMESTAMP"
          echo "SYNC_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Get latest upstream code
        if: steps.check_commits.outputs.has_new_commits == 'true'
        run: |
          # Simply copy the latest upstream code to our branch
          git reset --hard upstream/main
          echo "✅ Updated branch with latest upstream code"

      - name: Push sync branch
        if: steps.check_commits.outputs.has_new_commits == 'true'
        run: |
          git push origin $SYNC_BRANCH

      - name: Create PR with upstream changes
        if: steps.check_commits.outputs.has_new_commits == 'true'
        run: |
          # Create PR using GitHub API via curl with PAT
          curl -X POST \
            -H "Authorization: token ${{ secrets.UVKILL_SYNC_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/manascb1344/uvkill/pulls \
            -d @- << EOF
          {
            "title": "🔄 Sync with upstream NPKill",
            "head": "${{ env.SYNC_BRANCH }}",
            "base": "main",
            "body": "## 🔄 Upstream Sync\n\nThis PR brings the latest changes from the upstream NPKill repository.\n\n**Upstream commit:** \`${{ steps.check_commits.outputs.upstream_latest }}\`\n**Sync timestamp:** $(date)\n\n### Changes included:\n$(git log --oneline HEAD~10..HEAD | head -10)\n\n### Review checklist:\n- [ ] Review all changes for compatibility with UVKill\n- [ ] Test that Python virtual environment detection still works\n- [ ] Verify that UVKill-specific modifications are preserved\n- [ ] Update version number if needed\n- [ ] Test the build and functionality\n\nAuto-generated by GitHub Actions 🤖"
          }
          EOF

          echo "✅ PR created successfully!"

      - name: Cleanup merged/closed PR branches
        run: |
          echo "🧹 Checking for branches with merged or closed PRs..."

          # Get all remote branches except main and HEAD
          git branch -r --format='%(refname:short)' | grep -v 'origin/HEAD' | grep -v 'origin/main' | grep -v '^origin$' | sed 's/origin\///' | while read -r branch; do
            echo "Checking branch: $branch"
            
            # Check if PR exists for this branch
            PR_INFO=$(gh pr list --state all --json number,headRefName,state,mergedAt --jq ".[] | select(.headRefName == \"$branch\")" 2>/dev/null || echo 'null')
            
            if [ "$PR_INFO" != "null" ] && [ "$PR_INFO" != "" ]; then
              PR_STATE=$(echo "$PR_INFO" | jq -r '.state // "unknown"')
              PR_MERGED_AT=$(echo "$PR_INFO" | jq -r '.mergedAt // null')
              PR_NUMBER=$(echo "$PR_INFO" | jq -r '.number // "unknown"')
              
              echo "  PR #$PR_NUMBER: $PR_STATE"
              
              # Delete branch if PR is merged or closed
              if [ "$PR_STATE" = "MERGED" ] || [ "$PR_STATE" = "CLOSED" ]; then
                echo "  🗑️  Deleting branch '$branch' (PR #$PR_NUMBER is $PR_STATE)"
                
                # Delete remote branch
                git push origin --delete "$branch" 2>/dev/null || echo "    ⚠️  Failed to delete remote branch '$branch'"
                
                # Delete local branch if it exists
                git branch -D "$branch" 2>/dev/null || echo "    ℹ️  Local branch '$branch' doesn't exist"
                
                echo "  ✅ Cleaned up branch '$branch'"
              else
                echo "  ℹ️  Keeping branch '$branch' (PR #$PR_NUMBER is $PR_STATE)"
              fi
            else
              echo "  ℹ️  No PR found for branch '$branch' - keeping it"
            fi
          done

          echo "✅ Branch cleanup completed"

      - name: Cleanup on failure
        if: failure()
        run: |
          # Clean up any partial state
          git reset --hard HEAD
          git checkout main
          echo "🧹 Cleaned up failed sync attempt"
